In [ ]:
import numpy as np

# The Basics

In [ ]:
a = np.array([
              [1, 2, 3],
              [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a.nbytes

48

# Accessing/Changing elements

In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10 ,11 ,12, 13, 14]])

In [ ]:
a[1, -2]

13

In [ ]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:, -1]

array([ 7, 14])

In [ ]:
a[:, :]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a[1, 1:6:2]

array([ 9, 11, 13])

In [ ]:
a[1, 1] = 100
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8, 100,  10,  11,  12,  13,  14]])

In [ ]:
a[1, 2:] = 99
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8, 100,  99,  99,  99,  99,  99]])

In [ ]:
b = np.array([[
               [1,2],
               [3, 4]
              ],
              [
               [5, 6],
               [7, 8]
              ]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
b[0, 0]

array([1, 2])

In [ ]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

# Initialize arrray types

In [ ]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones((2, 3, 4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [ ]:
np.full((2, 3, 4), 99, dtype='float')

array([[[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [99., 99., 99., 99.]],

       [[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [99., 99., 99., 99.]]])

In [ ]:
np.random.rand(2, 3, 4)

array([[[0.42466042, 0.6350687 , 0.02260266, 0.86636136],
        [0.70228754, 0.28496984, 0.63658261, 0.31801284],
        [0.2127647 , 0.87537551, 0.59166387, 0.63270241]],

       [[0.11499584, 0.20103765, 0.32224526, 0.87201579],
        [0.40802749, 0.14485466, 0.46680983, 0.53973548],
        [0.38381712, 0.75445923, 0.41927258, 0.17651435]]])

In [ ]:
np.random.randint(-10, 10, size=(2, 3, 4))

array([[[  1,   6,  -9,   9],
        [ -1,  -6, -10,   9],
        [  8,  -7,  -4,  -9]],

       [[ -3,   8,  -3,   4],
        [ -2,  -6,   3,   8],
        [ -1,  -2,   5,  -4]]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Create a matrix 11 by 11 that the surounding are 1 and the center is 9. The other should be zero.

In [ ]:
ans = np.zeros((11, 11))
(ans[:, 0], ans[:, -1], ans[0, :], ans[-1, :]) = (1, 1, 1, 1)
ans[5, 5] = 9
ans

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 9., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ans = np.ones((11, 11))
temp = np.zeros((9, 9))
temp[4, 4] = 9
ans[1:-1, 1:-1] = temp
ans

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 9., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# Error
x = np.array([1, 2, 3])
y = x
y[0] = 32

print(x)
print(y)

[32  2  3]
[32  2  3]


In [ ]:
# Solution
# Error
x = np.array([1, 2, 3])
y = x.copy()
y[0] = 32

print(x)
print(y)

[1 2 3]
[32  2  3]


# Mathematics

In [ ]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 33

array([0.03030303, 0.06060606, 0.09090909, 0.12121212])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
b = np.random.rand(1, 4)
b

array([[0.55141684, 0.2504683 , 0.2510657 , 0.42052107]])

In [ ]:
a + b

array([[1.55141684, 2.2504683 , 3.2510657 , 4.42052107]])

In [ ]:
np.sin(a* b)

array([[0.5238946 , 0.48024727, 0.68397455, 0.99381388]])

## Algebra

In [ ]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.random.rand(3, 3)
c

array([[0.93587929, 0.18420167, 0.96438426],
       [0.80763974, 0.3016113 , 0.03368245],
       [0.86031828, 0.32927449, 0.49279078]])

In [ ]:
np.linalg.det(c)

0.06697084826393541

## Statistics

In [ ]:
stats = np.array([[1, 5, 5], [5, 9, -1]])
stats

array([[ 1,  5,  5],
       [ 5,  9, -1]])

In [ ]:
stats.min()

-1

In [ ]:
stats.min(axis=1)

array([ 1, -1])

In [ ]:
stats.min(axis=0)

array([ 1,  5, -1])

In [ ]:
stats.max()

9

In [ ]:
stats.max(axis=1)

array([5, 9, 5])

In [ ]:
stats.sum(axis=0)

array([ 6, 14,  4])

# Reorganizing arrays

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a.reshape(8, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
a.reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
v1 = a[0, :]
v2 = a[1, :]

np.vstack([v1, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
v1 = v1.reshape((2, 2))
v2 = v2.reshape((2, 2))

np.hstack((v1, v2, v2 , v1))

array([[1, 2, 5, 6, 5, 6, 1, 2],
       [3, 4, 7, 8, 7, 8, 3, 4]])

# Miscellaneous

## Load data from file

In [ ]:
# txt files
data = np.genfromtxt('data.txt', delimiter=',')
data = data.astype('int32')
data

array([[  -119,     36,     19,   1241,    244,    850,    237,      2,
         81700],
       [  -119,     36,     37,   1018,    213,    663,    204,      1,
         67000],
       [  -121,     38,     43,   1009,    225,    604,    218,      1,
         67000],
       [  -120,     35,     19,   2310,    471,   1341,    441,      3,
        166900],
       [  -122,     38,     15,   3080,    617,   1446,    599,      3,
        194400],
       [  -118,     34,     31,   2402,    632,   2830,    603,      2,
        164200],
       [  -118,     33,     45,    972,    249,   1288,    261,      2,
        125000],
       [  -119,     35,     37,    736,    166,    564,    138,      2,
         58300],
       [  -121,     37,     36,   1089,    182,    535,    170,      4,
        252600],
       [  -117,     32,     16,   3936,    694,   1935,    659,      4,
        231200],
       [  -117,     33,     27,   2097,    325,   1217,    331,      5,
        222500],
       [  -117,     3

In [ ]:
data > 100 

array([[False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True, False,  True, False, False,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True,  True,  True, False, 

In [ ]:
data[data > 100]

array([  1241,    244,    850,    237,  81700,   1018,    213,    663,
          204,  67000,   1009,    225,    604,    218,  67000,   2310,
          471,   1341,    441, 166900,   3080,    617,   1446,    599,
       194400,   2402,    632,   2830,    603, 164200,    972,    249,
         1288,    261, 125000,    736,    166,    564,    138,  58300,
         1089,    182,    535,    170, 252600,   3936,    694,   1935,
          659, 231200,   2097,    325,   1217,    331, 222500,    161,
          157, 153100,    570,    123,    189,    107, 181300,   3077,
          607,   1603,    595, 137500,   1590,    196,    654,    199,
       300000,   8814,   1307,   3450,   1258, 414300,   1445,    256,
          849,    255, 126300,   1775,    296,    937,    305,  83400,
         2994,    543,   1651,    561, 241500,   2021,    528,   1410,
          480, 115400,   6131,   1040,   4049,    940, 150700,   1401,
          218,    667,    225, 484700,   3587,   1030,   2259,    979,
      

## Boolean masking & Advance Indexing

In [ ]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a[:, [0, -1]]

array([[1, 4],
       [5, 8]])

In [ ]:
a[:, [False, False, True, False]]

array([[3],
       [7]])

In [ ]:
np.any(data > 50, axis=0)

array([False, False,  True,  True,  True,  True,  True, False,  True])

In [ ]:
np.all(data > 50, axis=0)

array([False, False, False,  True, False,  True, False, False,  True])

In [ ]:
(~(data < 50) & (data < 100))

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

Create a 6 * 5 matrix and the data should be from 1 to 30.

In [ ]:
ans = np.arange(30) + 1
ans = ans.reshape((6, 5))
ans

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

How to index `[[11, 12], [16, 17]]`?

In [ ]:
ans[2:4, 0:2]

array([[11, 12],
       [16, 17]])

How to index [2, 8, 14, 20]?

In [ ]:
ans.reshape((1, 30))[0][1:20:6]

array([ 2,  8, 14, 20])

How to index [4, 5, 24, 25, 29, 30]?

In [ ]:
ans[[0, -2, -1], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])